#This code is to generate plots from the merged VCF file (max 4)
#The input VCF file should be generated by SURVIVOR and 

####
#Check and install!
list.of.packages <- c("optparse","VennDiagram","ggplot2","reshape2")
new.packages <- list.of.packages[!(list.of.packages %in% installed.packages()[,"Package"])]
if(length(new.packages)) install.packages(new.packages)
rm(list.of.packages, new.packages)
####

library("optparse")
library("VennDiagram")

option_list = list(
  make_option(c("-i", "--input_vcf"), type="character",default="4_naibrs_merged.vcf", #NULL,
              help="merged VCF dataset input file name", metavar="character"),
  make_option(c("-t", "--type"), type="character", default=NULL,
				      help="SV type to keep [DEL, DUP, INV] [default= %default]", metavar="character")
  #output will be by default the same as the input path
  #make_option(c("-o", "--out"), type="character", default=NULL,
	#			      help="output file name [default= %default]", metavar="character")
);

opt_parser = OptionParser(option_list=option_list);
opt = parse_args(opt_parser);


if (!is.na(opt$input_vcf)) {
  vcf_file <- opt$input_vcf
  cat(sprintf("\nFile to be plotted:\n%s\n\n",opt$input_vcf))
  file_name <- opt$input_vcf
  file_name <- gsub('.{4}$', '_', file_name)
  bedpeout <- paste0(file_name,"list.bedpe")
} else {
  stop("date parameter must be provided. See script usage (--help)")
}

#Get samples names
files_names <- system(sprintf("bcftools query -l %s",vcf_file),intern = T)
number_of_samples <- (length(files_names))

#Generating comparison matrix
comparison_matrix <- sprintf("SURVIVOR genComp %s 0 %scomparison_matrix.txt", vcf_file, file_name)
print(comparison_matrix)
system(comparison_matrix)

#Plot comparison matrix

if (file.info(paste0(file_name,"comparison_matrix.txt"))$size == 0 )
{
  stop("All values filtered out!")
} 


t=read.table(paste0(file_name,"comparison_matrix.txt"),header=F)
dst <- data.matrix(t(t))
pdf(file = paste0(file_name,"figures.pdf"))


# image(1:nrow(dst), 1:ncol(dst),log(dst), col=rev(heat.colors(10)),axes=F, xlab="", ylab="")
# grid(col='black',nx=nrow(dst),ny=ncol(dst),lty=1)

library(ggplot2)
library(reshape2)

tt<-data.frame(t)
tt$row <- paste("L", 1:number_of_samples, sep='')
tt_melt <- melt(tt)
ggplot(data=tt_melt,
       aes(x=variable, y=row, fill=value)) + geom_tile() +
       geom_text(aes(label=value), color='white') +
       theme_bw() + scale_fill_gradient(low = "yellow", high = "red",)

dev.off()

if(number_of_samples > 5) {
number_of_samples = 5      # plot only the first 5
  }

#remove path
files_names <- sub('.*/', '', files_names)
#Keep the names of Naibr and linkedSV files
files_names <- sub(x = files_names, pattern = "_filtered_sorted_merged.bedpe","",ignore.case = T)
files_names <- sub(x = files_names, pattern = "_final.naibr_sv_calls","_naibr",ignore.case = T)
files_names <- sub(x = files_names, pattern = "_final.phased.bam.filtered_large_svcalls","_linkedsv",ignore.case = T)
files_names <- gsub(x = files_names, pattern = "\\.BLR","",ignore.case = T)
#remove the bedpe if not Naibr nor linkedSV
files_names <- sub(x = files_names, pattern = ".bedpe","",ignore.case = T) 

#make new lines for every dot
files_names <- gsub(x = files_names, pattern = "[\\._]","\n",ignore.case = T)

#Extract list of shared regions
intersection_list <- paste0(file_name,"intersection_matrix.txt")
perl_code <- sprintf( 'perl -ne \'print "$1\\n" if /SUPP_VEC=([^,;]+)/\' %s | sed -e \'s/\\(.\\)/\\1 /g\' > %s',
                      vcf_file, intersection_list)
system(perl_code)


#Save the intersection matrix
system(sprintf("SURVIVOR vcftobed %s -1 -1 %s_tmp",vcf_file,bedpeout))
system(sprintf("paste %1$s_tmp %2$s > %1$s && rm %1$s_tmp",bedpeout,intersection_list))


#Plotting the intersections
t=read.table(intersection_list ,header=F)

#Generate the plotting matrix
list_to_plot=list()
for (len in 1:number_of_samples) {
  list_to_plot <- append(list_to_plot, list(which(t[,len]==1)))
  }

#print(list_to_plot)
names(list_to_plot) <- files_names[1:number_of_samples]

myfill <- c("pink", "orange" ,"green","blue","red")
myfill <- myfill[1:number_of_samples]
venn.diagram(list_to_plot, output=True,
            #image  
            filename =  paste0(file_name,"overlap.png"),
            main = opt$type, #print.mode = "percent",
            main.cex = .7,
            height = 1000 , 
            width = 1000 , 
            resolution = 300,
            compression = "lzw",
            imagetype = "png",
            #cyrcles
            fill = myfill ,
            alpha = rep(0.5,number_of_samples),
            cex = .5, #size numbers
            lty = 4, #dotted line
            lwd = .2, #thickness
            #Set names
            cat.cex = 0.3,
            cat.default.pos = "outer", #or text
            cat.dist = 0
          );

system(sprintf("rm %s",intersection_list))
